name: "Create and publish container images"

on:
  push:
    branches:
      - release/sirosid
    tags:
      - 'v*.*.**'
      - 'v*.*.**-sirosid.*'

env:
  REGISTRY: "ghcr.io"
  NAME: "${{ github.repository }}"

jobs:
  "build-and-push-image":
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
      packages: "write"

    steps:
      # GHCR doesn't accept uppercase characters in repository path \_o_/
      - name: "Extract lowercase image name"
        id: "lowercaser"
        run: "echo \"name=${NAME}\" | tr '[[:upper:]]' '[[:lower:]]' >> \"${GITHUB_OUTPUT}\""

      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Setup Buildx for Docker"
        uses: "docker/setup-buildx-action@ba31df4664624f17e1b1ef1c9c85ed1ca9463a6d"

      - name: "Log in to the Container registry"
        uses: "docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1"
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Extract metadata for Docker"
        id: "meta"
        uses: "docker/metadata-action@v5"
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercaser.outputs.name }}
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=unstable,enable=${{ github.ref == 'refs/heads/release/sirosid' }}

      - name: "Build and push Docker image"
        uses: "docker/build-push-action@v5"
        with:
          file: "Dockerfile"
          context: "."
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
